CREATE TABLE "FeedItems" (
  "id" SERIAL PRIMARY KEY,
  "caption" VARCHAR(1024),
  "url" VARCHAR(1024),
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);